### ISSUE TITLE
New US East AWS Region

### ISSUE THREAD

**Issue by krishatcher** [rtfpessoa/teamcity-aws-elasticbeanstalk-plugin#1]
AWS now has a second "US East" region that needs to be added to the system as an option.

**Comment by rtfpessoa** [comment]
Thanks for the contribution. Just merged it.

You can start using the new version from here: https://18-65077465-gh.circle-artifacts.com/0/home/ubuntu/teamcity-aws-elasticbeanstalk-plugin/build/build/distributions/aws-elasticbeanstalk-plugin-agent.zip

**Comment by rtfpessoa** [comment]
I think I pasted the wrong link before.

You might need https://18-65077465-gh.circle-artifacts.com/0/home/ubuntu/teamcity-aws-elasticbeanstalk-plugin/build/build/distributions/aws-elasticbeanstalk-plugin.zip
