### ISSUE TITLE
EU-London region missing

### ISSUE THREAD

**Issue by rrpatel547** [rtfpessoa/teamcity-aws-elasticbeanstalk-plugin#14]
Are you able to add the london region to the dropdown? Alternatively could you make it a text box instead.

**Comment by rtfpessoa** [comment]
That would be nice. Maybe add a not with the available regions so people could copy paste and then allow others. Or maybe an extra text box.

Either way if you could do PR would be great.

**Comment by rrpatel547** [comment]
I have added the region but an error shows when trying to use it, I have updated the version number of the AWS SDK but I suspect there is more to it, I am not a java developer so would be good if someone could look at what I have done, it should be in the pull request.

**Comment by rtfpessoa** [comment]
My bad. This was done before I will check.

**Comment by rtfpessoa** [comment]
Released as version v1.0.6
