### ISSUE TITLE
Unsafe chars in object key

### ISSUE THREAD

**Issue by campbellmcneill** [rtfpessoa/teamcity-aws-elasticbeanstalk-plugin#5]
Hey AWS S3 object keys can have :: chars in them. That's a legitimate key name.

The validator is rejecting those, the regex obviously disallowing them.

Is there a workaround to this or should I write a patch?

**Comment by rtfpessoa** [comment]
@campbellmcneill most code was taken from https://github.com/JetBrains/teamcity-aws-codedeploy-plugin and validators are also default.

Feel free to send a pr with a fix.

**Comment by rtfpessoa** [comment]
@campbellmcneill released ad version `1.0.3` https://github.com/rtfpessoa/teamcity-aws-elasticbeanstalk-plugin/releases/tag/v1.0.3
