### ISSUE TITLE
Add option to skip creation of ApplicationVersion if one already exists.

### ISSUE THREAD

**Issue by danieljimenez** [rtfpessoa/teamcity-aws-elasticbeanstalk-plugin#7]
I'd like to add an option to skip the creation of an ApplicationVersion if one already exists. 

Our use case is that we deploy to EB from TeamCity to stage, then to pre-prod, production, etc. All from the same build artifacts.

**Comment by rtfpessoa** [comment]
Feel free to send a PR.

Sounds like a good use case, probably more people are doing something similar.

**Comment by danieljimenez** [comment]
Will do! Thanks for a great plugin!

**Comment by rtfpessoa** [comment]
Released as version [v1.0.4](https://github.com/rtfpessoa/teamcity-aws-elasticbeanstalk-plugin/releases/tag/v1.0.4)
